In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.2.4


In [5]:
# array using list
arr = np.array([20,25,30,35])
print(arr)
print(type(arr))

[20 25 30 35]
<class 'numpy.ndarray'>


In [6]:
# array using tuple
arr = np.array((30,40,50,60))
print(arr)
print(type(arr))

[30 40 50 60]
<class 'numpy.ndarray'>


In [11]:
a = np.array(56)
b = np.array([12,34,56])
c = np.array([[53,64,75,86],[87,64,34,73]])
d = np.array([[[53,64,75,86],[87,64,34,73]],[[46,56,75,65],[34,54,75,34]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
arr = np.array([21,34,53,64],ndmin=5)
print(arr)

[[[[[21 34 53 64]]]]]


### list vs array
 NumPy is:

Faster  
Uses less memory   
Supports vector operations  

In [13]:
# Python list
a = [1, 2, 3]

# NumPy array
b = np.array([1, 2, 3])

### Shape & Size

In [14]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)  
print(arr.size)   

(2, 3)
6


### Indexing & Slicing

In [15]:
arr = np.array([10, 20, 30, 40])

print(arr[0])     
print(arr[1:3]) 

10
[20 30]


In [18]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr[1,0])  

4


### Array Operations

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)   
print(a * b)   

[5 7 9]
[ 4 10 18]


no loop needed here while in list doing operation needs loop but in array we don't need loops for this purpose, this is called **vectorization**

### Built-in Functions

In [50]:
arr = np.array([1,2,3,4])

print(np.mean(arr)) 
print(np.sum(arr))   
print(np.max(arr)) 
print(np.var(arr))  
print(np.std(arr))

2.5
10
4
1.25
1.118033988749895


### Special Arrays

In [21]:
import numpy as np
a =np.zeros((2,2))
b =np.ones((3,3))
c =np.arange(0,10,2)
d =np.linspace(0,1,5)

print(a)
print(b)
print(c)
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### Reshaping Arrays

In [29]:
arr = np.array([1,2,3,4,5,6])
print(arr)
new_arr = arr.reshape(2,3)
print(new_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### Flattening

In [30]:
arr = np.array([1,2,3,4,5,6])
arr.flatten()

array([1, 2, 3, 4, 5, 6])

### Random Numbers

In [38]:
print(np.random.rand(3))
print(np.random.randint(1, 10, 5))

[0.26767088 0.11929431 0.13518656]
[1 3 8 7 1]


### Boolean Indexing

In [39]:
arr = np.array([10, 20, 30, 40])
print(arr[arr > 20])  

[30 40]


### Broadcasting

In [ ]:
a = np.array([1,2,3])
b = 3
print(a * b)  

[3 6 9]


NumPy automatically expands b

### Matrix Operations

In [44]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.dot(a, b))

[[19 22]
 [43 50]]


### Axis Concept

In [47]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(np.sum(arr, axis=0))  
print(np.sum(arr, axis=1))  

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


## practice

Q1: Create Arrays

Create the following using NumPy:

Array from 1 to 10  
Array of all zeros (3×3)  
Array of all ones (2×4)  
Even numbers from 0 to 20  

In [54]:
arr1_10 = np.arange(1,11)
arr0s = np.zeros((3,3))
arr1s = np.ones((2,4))
arrEven= np.arange(0,21,2)

print(arr1_10)
print(arr0s)
print(arr1s)
print(arrEven)

[ 1  2  3  4  5  6  7  8  9 10]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 0  2  4  6  8 10 12 14 16 18 20]


Find:

Dimension  
Shape  
Total elements  

In [55]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(2, 3)
6


linear algebra equation

In [100]:
cof = np.array([[1,1],[5,1]])
cons = np.array([3,1])

In [101]:
np.linalg.solve(cof,cons)

array([-0.5,  3.5])

In [102]:
cof = np.array([[1,1,4],[5,1,3],[1,2,3]])
cons = np.array([3,1,4])

In [103]:
np.linalg.solve(cof,cons)

array([-0.38095238,  1.47619048,  0.47619048])

### quadratic equation
5x2 + 6x + 2 = 0

In [104]:
a = 5
b = 6
c = 2

In [112]:
disc = np.square(b) - 4*(a*c)
disc

np.int64(-4)

In [113]:
sqt = np.sqrt(abs(disc))
sqt

np.float64(2.0)

In [114]:
-b + sqt/2*a

np.float64(-1.0)

In [115]:
-b - sqt/2*a

np.float64(-11.0)