In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.2.4


In [5]:
# array using list
arr = np.array([20,25,30,35])
print(arr)
print(type(arr))

[20 25 30 35]
<class 'numpy.ndarray'>


In [6]:
# array using tuple
arr = np.array((30,40,50,60))
print(arr)
print(type(arr))

[30 40 50 60]
<class 'numpy.ndarray'>


In [11]:
a = np.array(56)
b = np.array([12,34,56])
c = np.array([[53,64,75,86],[87,64,34,73]])
d = np.array([[[53,64,75,86],[87,64,34,73]],[[46,56,75,65],[34,54,75,34]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
arr = np.array([21,34,53,64],ndmin=5)
print(arr)

[[[[[21 34 53 64]]]]]
