In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.2.4


In [5]:
# array using list
arr = np.array([20,25,30,35])
print(arr)
print(type(arr))

[20 25 30 35]
<class 'numpy.ndarray'>


In [6]:
# array using tuple
arr = np.array((30,40,50,60))
print(arr)
print(type(arr))

[30 40 50 60]
<class 'numpy.ndarray'>


In [11]:
a = np.array(56)
b = np.array([12,34,56])
c = np.array([[53,64,75,86],[87,64,34,73]])
d = np.array([[[53,64,75,86],[87,64,34,73]],[[46,56,75,65],[34,54,75,34]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
arr = np.array([21,34,53,64],ndmin=5)
print(arr)

[[[[[21 34 53 64]]]]]


### list vs array
 NumPy is:

Faster  
Uses less memory   
Supports vector operations  

In [13]:
# Python list
a = [1, 2, 3]

# NumPy array
b = np.array([1, 2, 3])

### Shape & Size

In [14]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)  
print(arr.size)   

(2, 3)
6


### Indexing & Slicing

In [15]:
arr = np.array([10, 20, 30, 40])

print(arr[0])     
print(arr[1:3]) 

10
[20 30]


In [18]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr[1,0])  

4


### Array Operations

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)   
print(a * b)   

[5 7 9]
[ 4 10 18]


no loop needed here while in list doing operation needs loop but in array we don't need loops for this purpose, this is called **vectorization**

### Built-in Functions

In [20]:
arr = np.array([1,2,3,4])

print(np.mean(arr)) 
print(np.sum(arr))   
print(np.max(arr))   

2.5
10
4


### Special Arrays

In [21]:
import numpy as np
a =np.zeros((2,2))
b =np.ones((3,3))
c =np.arange(0,10,2)
d =np.linspace(0,1,5)

print(a)
print(b)
print(c)
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
